server:
  port: 8081
spring:
  application:
    name: ToDoApp
  mongodb:
    uri: mongodb://localhost:27017
    database: doto_application
jwt:
  secret: "mysupersecuresecretkeymysupersecuresecretkey" # at least 32 chars

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.mongodb.driver: INFO