spring:
  application:
    name: ToDoApp
  mongodb:
    uri:
    database: doto_application
jwt:
  secret: "mysupersecuresecretkeymysupersecuresecretkey" # at least 32 chars


logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.mongodb.driver: INFO